name: images-go

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
       go-version: '1.17.6'
    - name: Install Go Packages
      run: cd points && go get -t -v github.com/stretchr/testify/assert
    - name: Run Go Tests
      run: cd points && go test -coverprofile=coverage.out
