name: images-gon-pull_request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
       go-version: '1.17.6'
    - name: Install Go Packages
      run: cd points && source setup.sh && go get -t -v github.com/stretchr/testify/assert

    - name: Run Go Tests
      run: cd points && source setup.sh && go test -coverprofile=coverage.out
