name: images-gon-pull_request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
       go-version: '1.9.3' # The Go version to download (if necessary) and use.
    - name: Install Go Packages
      run: cd points && go get -t -v github.com/stretchr/testify/assert
    - name: Run Go Tests
      run: cd points && go test -coverprofile=coverage.out && go tool cover -html=coverage.out
